import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');
const isSmallDevice = width < 375;
const isMediumDevice = width >= 375 && width < 414;
const isLargeDevice = width >= 414;

// Helper functions for responsive sizing
const normalizeSize = (size) => {
  if (isSmallDevice) return size * 0.85;
  if (isLargeDevice) return size * 1.15;
  return size;
};

const responsivePadding = (size) => {
  if (isSmallDevice) return size * 0.8;
  if (isLargeDevice) return size * 1.2;
  return size;
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  scrollContent: {
    padding: responsivePadding(24),
    paddingBottom: responsivePadding(40),
  },
  title: {
    fontSize: normalizeSize(28),
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: normalizeSize(8),
    color: '#1e293b',
    letterSpacing: -0.5,
    maxWidth: '100%',
  },
  subtitle: {
    fontSize: normalizeSize(16),
    textAlign: 'center',
    marginBottom: responsivePadding(24),
    color: '#64748b',
    fontWeight: '400',
    maxWidth: '100%',
    paddingHorizontal: responsivePadding(10),
  },
    contactItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    backgroundColor: 'white',
    marginBottom: 8,
    borderRadius: 6,
  },
  serverStatus: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: responsivePadding(24),
    padding: responsivePadding(16),
    backgroundColor: 'white',
    borderRadius: normalizeSize(16),
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    minHeight: normalizeSize(60),
  },
  serverStatusText: {
    fontSize: normalizeSize(16),
    color: '#475569',
    fontWeight: '500',
    flexShrink: 1,
  },
  serverStatusValue: {
    fontSize: normalizeSize(16),
    fontWeight: '700',
    marginLeft: normalizeSize(8),
    flexShrink: 1,
  },
  sensorSection: {
    marginBottom: responsivePadding(24),
    backgroundColor: 'white',
    padding: responsivePadding(20),
    borderRadius: normalizeSize(20),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  sectionTitle: {
    fontSize: normalizeSize(20),
    fontWeight: '700',
    marginBottom: normalizeSize(16),
    color: '#1e293b',
    letterSpacing: -0.3,
    textAlign: 'center',
  },
  sensorRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: normalizeSize(12),
    flexWrap: 'wrap',
  },
  sensorData: {
    width: isSmallDevice ? '100%' : '48%',
    alignItems: 'center',
    padding: responsivePadding(16),
    backgroundColor: '#f8fafc',
    borderRadius: normalizeSize(12),
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: isSmallDevice ? normalizeSize(12) : 0,
    minHeight: normalizeSize(100),
  },
  sensorLabel: {
    fontSize: normalizeSize(14),
    fontWeight: '600',
    marginBottom: normalizeSize(8),
    color: '#3b82f6',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  sensorValue: {
    fontSize: normalizeSize(20),
    fontWeight: '700',
    color: '#1e293b',
    textAlign: 'center',
  },
  totalText: {
    fontWeight: '700',
    marginTop: normalizeSize(8),
    color: '#1e293b',
    fontSize: normalizeSize(14),
    textAlign: 'center',
  },
  buttonRow: {
    flexDirection: isSmallDevice ? 'column' : 'row',
    justifyContent: 'space-between',
    marginBottom: responsivePadding(24),
    gap: normalizeSize(12),
  },
  monitorButton: {
    flex: isSmallDevice ? 0 : 1,
    padding: responsivePadding(16),
    borderRadius: normalizeSize(14),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: 'transparent',
    minHeight: normalizeSize(55),
    marginBottom: isSmallDevice ? normalizeSize(10) : 0,
  },
  startButton: {
    backgroundColor: '#10b981',
    borderColor: '#10b981',
  },
  stopButton: {
    backgroundColor: '#ef4444',
    borderColor: '#ef4444',
  },
  clearButton: {
    backgroundColor: '#64748b',
    borderColor: '#64748b',
  },
  monitorButtonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: normalizeSize(14),
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  loadingContainer: {
    alignItems: 'center',
    marginBottom: responsivePadding(24),
    padding: responsivePadding(20),
    backgroundColor: '#f1f5f9',
    borderRadius: normalizeSize(16),
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  loadingText: {
    marginTop: normalizeSize(12),
    color: '#64748b',
    fontSize: normalizeSize(14),
    fontWeight: '500',
    textAlign: 'center',
  },
  resultContainer: {
    padding: responsivePadding(20),
    borderRadius: normalizeSize(16),
    borderWidth: 1,
    marginBottom: responsivePadding(24),
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
    borderColor: '#e2e8f0',
  },
  resultTitle: {
    fontSize: normalizeSize(18),
    fontWeight: '700',
    marginBottom: normalizeSize(8),
    color: '#1e293b',
    letterSpacing: -0.3,
    textAlign: 'center',
  },
  resultText: {
    fontSize: normalizeSize(22),
    fontWeight: '800',
    marginBottom: normalizeSize(12),
    color: '#3b82f6',
    textAlign: 'center',
  },
  resultDescription: {
    fontSize: normalizeSize(14),
    marginBottom: normalizeSize(6),
    color: '#475569',
    lineHeight: normalizeSize(20),
    textAlign: 'center',
  },
  detectionNote: {
    fontSize: normalizeSize(12),
    fontStyle: 'italic',
    color: '#94a3b8',
    marginTop: normalizeSize(8),
    fontWeight: '400',
    textAlign: 'center',
  },
  historySection: {
    marginBottom: responsivePadding(24),
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalizeSize(16),
    flexWrap: 'wrap',
  },
  historyCount: {
    color: '#64748b',
    fontSize: normalizeSize(13),
    fontWeight: '500',
  },
  historyItem: {
    backgroundColor: 'white',
    padding: responsivePadding(14),
    borderRadius: normalizeSize(12),
    marginBottom: normalizeSize(10),
    borderLeftWidth: 4,
    borderLeftColor: '#3b82f6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  historyTime: {
    fontSize: normalizeSize(12),
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: normalizeSize(4),
    letterSpacing: 0.2,
  },
  historyText: {
    fontSize: normalizeSize(12),
    color: '#64748b',
    marginBottom: normalizeSize(2),
    lineHeight: normalizeSize(16),
  },
   contactInfo: {
    flex: 1,
  },
  contactName: {
    fontWeight: '600',
    fontSize: 14,
  },
  contactPhone: {
    color: '#666',
    fontSize: 12,
  },
  deleteButton: {
    color: '#e74c3c',
    fontWeight: '600',
  },
  emptyText: {
    textAlign: 'center',
    color: '#999',
    fontStyle: 'italic',
    marginVertical: 20,
  },
  infoContainer: {
    backgroundColor: '#eff6ff',
    padding: responsivePadding(18),
    borderRadius: normalizeSize(16),
    borderWidth: 1,
    borderColor: '#bfdbfe',
    marginBottom: responsivePadding(24),
  },
  infoTitle: {
    fontSize: normalizeSize(16),
    fontWeight: '700',
    marginBottom: normalizeSize(10),
    color: '#1e40af',
    letterSpacing: -0.2,
    textAlign: 'center',
  },
  infoText: {
    fontSize: normalizeSize(13),
    marginBottom: normalizeSize(5),
    color: '#374151',
    lineHeight: normalizeSize(18),
    fontWeight: '400',
    textAlign: 'center',
  },
  feedbackSection: {
    marginBottom: responsivePadding(24),
  },
  eventItem: {
    backgroundColor: 'white',
    padding: responsivePadding(16),
    borderRadius: normalizeSize(14),
    marginBottom: normalizeSize(10),
    borderLeftWidth: 4,
    borderLeftColor: '#f97316',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  eventTime: {
    fontSize: normalizeSize(12),
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: normalizeSize(4),
    letterSpacing: 0.2,
  },
  eventText: {
    fontSize: normalizeSize(12),
    color: '#64748b',
    marginBottom: normalizeSize(2),
    lineHeight: normalizeSize(16),
  },
  feedbackButton: {
    backgroundColor: '#3b82f6',
    padding: responsivePadding(12),
    borderRadius: normalizeSize(10),
    marginTop: normalizeSize(10),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#2563eb',
  },
  feedbackButtonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: normalizeSize(13),
    letterSpacing: 0.3,
  },
  noEventsText: {
    fontSize: normalizeSize(14),
    color: '#94a3b8',
    textAlign: 'center',
    marginVertical: responsivePadding(20),
    fontWeight: '500',
    fontStyle: 'italic',
  },
  // Header styles
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: responsivePadding(16),
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(59, 130, 246, 0.2)',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  headerButtons: {
    flexDirection: 'row',
    gap: normalizeSize(12),
    alignItems: 'center',
  },
  settingsButton: {
    padding: normalizeSize(10),
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    borderRadius: normalizeSize(10),
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    minWidth: normalizeSize(44),
    minHeight: normalizeSize(44),
    justifyContent: 'center',
    alignItems: 'center',
  },
  panicButton: {
    padding: normalizeSize(10),
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderRadius: normalizeSize(10),
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
    minWidth: normalizeSize(44),
    minHeight: normalizeSize(44),
    justifyContent: 'center',
    alignItems: 'center',
  },
  panicButtonDisabled: {
    opacity: 0.5,
  },
  settingsContainer: {
    padding: responsivePadding(20),
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: responsivePadding(14),
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: normalizeSize(12),
    marginBottom: normalizeSize(12),
  },
  settingLabel: {
    color: '#1e293b',
    fontSize: normalizeSize(14),
    fontWeight: '500',
    flex: 1,
  },
  settingSubtitle: {
    color: '#3b82f6',
    fontSize: normalizeSize(16),
    fontWeight: '700',
    marginBottom: normalizeSize(12),
    marginTop: normalizeSize(16),
    textAlign: 'center',
  },
  saveButton: {
    backgroundColor: '#3b82f6',
    padding: responsivePadding(14),
    borderRadius: normalizeSize(10),
    alignItems: 'center',
    marginTop: normalizeSize(16),
  },
  saveButtonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: normalizeSize(14),
  },
  warningText: {
    color: '#f59e0b',
    fontSize: normalizeSize(10),
    fontWeight: '500',
    marginTop: normalizeSize(4),
    textAlign: 'center',
  },
  // Estados de color
  statusConnected: {
    color: '#10b981',
  },
  statusDisconnected: {
    color: '#ef4444',
  },
  statusChecking: {
    color: '#f59e0b',
  },
  configContainer: {
    padding: 16,
    marginBottom: 20,
    backgroundColor: '#f8f9fa',
    borderRadius: 10,
  },
  contactForm: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
    color: '#34495e',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 6,
    padding: 12,
    marginBottom: 12,
    backgroundColor: 'white',
  },
  textArea: {
    height: 120,
    textAlignVertical: 'top',
  },
});

// Colores adicionales para usar en componentes
export const colors = {
  primary: '#3b82f6',
  success: '#10b981',
  danger: '#ef4444',
  warning: '#f59e0b',
  info: '#3b82f6',
  light: '#f8fafc',
  dark: '#1e293b',
  gray: '#64748b',
};